# Generated by Django 6.0.3 on 2026-03-27 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_user_username_post_commentary"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
